# ##### Mariadb Galera Cluster LoadBalancer Service #####
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mariadb-lb
#   labels:
#     app: mariadb-lb
# spec:
#   type: LoadBalancer
#   loadBalancerSourceRanges:
#   - 0.0.0.0/0
#   ports:
#   - name: mariadb-lb
#     port: 13306
#     targetPort: 3306
#     protocol: TCP
#   selector:
#     app: mariadb

##### Mariadb Galera Cluster Service #####
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: mariadb

##### Secret for store password with base64 #####
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
type: Opaque
data:
  # Root password (base64): echo -n 'apirath-lab' | base64
  password: YXBpcmF0aC1sYWI=

##### Mariadb Galera Cluster StatefulSet Template #####
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: "mariadb"
  replicas: 3
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: labdocker/galara-mariadb:10.1
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: DISCOVERY_SERVICE
          value: etcd-client:2379
        - name: XTRABACKUP_PASSWORD
          value: password
        - name: CLUSTER_NAME
          value: galera-mariadb-cluster
        # - name: MYSQL_DATABASE
        #   value: mydatabase
        # - name: MYSQL_USER
        #   value: myuser
        # - name: MYSQL_PASSWORD
        #   value: myuserpassword
        readinessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --readiness
          initialDelaySeconds: 180
          periodSeconds: 1
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --liveness
          initialDelaySeconds: 210
          periodSeconds: 1
        volumeMounts:
        - name: mysql-datadir
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-datadir
      annotations:
        volume.beta.kubernetes.io/storage-class: gcp-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: gcp-storage
      resources:
        requests:
          storage: 10Gi
